apiVersion: v1
kind: Service
metadata:
  labels:
    app.data-infra.io/name: data-extraction-notify-server
  name: data-extraction-notify-server
  namespace: starboard-data-infra
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app.data-infra.io/name: data-extraction-notify-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.data-infra.io/name: data-extraction-notify-server
  name: data-extraction-notify-server
  namespace: starboard-data-infra
spec:
  replicas: 2
  selector:
    matchLabels:
      app.data-infra.io/name: data-extraction-notify-server
  template:
    metadata:
      labels:
        app.data-infra.io/name: data-extraction-notify-server
    spec:
      containers:
      - name: data-api
        image: 129862287110.dkr.ecr.us-east-2.amazonaws.com/data-infra/data-api-server:${tag}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: conf-volume
          mountPath: "/etc/data-extraction-notify/conf/"
          readOnly: true
        ports:
          - containerPort: 80
      volumes:
      - name: conf-volume
        projected:
          sources:
          - configMap:
              name: data-extraction-notify-conf
